### ISSUE TITLE
Output from SQL query truncated even if scrollback is large enough.

### ISSUE THREAD

**Issue by beaucoder** [ioquatix/script-runner#60] opened 2017-01-01 22:10 UTC
Running SQLite3 Query in Ruby 2.3.3 on Linux / Ubuntu 16.04. 387 lines produced in query but only 217 show in script-runner. Scrollback of 555 or larger (up t0 3,000) does not help.

How to fix?

Thank you, Ken Wagner
beaucoder@gmail.com

**Comment by beaucoder** [comment] 2017-01-02 00:21
Hi Huba,

Only a very, very few queries are that large.

Most are under 1,000.

Any help would be greatly appreciated as Script-runner is hugely helpful.

Many thanks,

Ken Wagner

**Comment by ioquatix** [comment] 2017-01-02 11:30
Uh, the scroll back option does still work but it might have changed the name, however I wonder if this is really the issue. we need to reproduce this issue with a simple script, e.g. generate 500 lines of output and see what is visible/scrollable.

**Comment by beaucoder** [comment] 2017-01-02 11:58
Hi Samuel,

The output varies from about 170 to 260 lines or so out of 347 total. 
Depends somewhat on just when I hit Alt + x. Using Ubuntu 16.04, Ruby 
2.3.3, SQLite3 3.15.2. It's a simple script using the SQLite3 chinook.db 
sample DB:

"select title, name from albums, artists where albums.artistid = 
artists.artistid order by name;".

Yields 347 rows. Script-runner shows random numbers as noted above, but 
never all whether using the default 555 scrollback or other numbers.

When executing the Ruby script directly in a terminal the rows are 
always complete. Just not in Scirpt-Runner.

If you "select * from tracks;" you will get tons of lines: 3,503.

To duplicate: download the chinook.db from Sqlite web site. Use Ruby and 
'sqlite3-ruby' with "require 'sqlite3' to execute a SQL query. Then use 
'puts' to show each row in the terminal screen.

Any questions, let me know.

Regards,

Ken Wagner

**Comment by ioquatix** [comment] 2017-01-02 11:59
Let me get this straight, a simple query against the database gives 3,500 lines of output correctly, but a more complex query truncates the data arbitrarily?

**Comment by huba** [comment] 2017-01-02 12:07
Well, this is quite weird. I did:

```ruby
0..500.times do |n|
	puts "%5d another one!" % n
end
```

and it only partially prints line 331 before it finishes. [see here](http://imgur.com/a/sgoWS)

It seems like the pty gets destroyed too soon.

**Comment by ioquatix** [comment] 2017-01-02 12:12
ah interesting, yeah that makes sense (pty getting destroyed too soon). I guess I need to look at the correct way to know that the output is complete and the process is finished.

**Comment by beaucoder** [comment] 2017-01-02 12:17
Thank, Samuel, for your prompt reply.

Script-runner is a jewel. Very much appreciated.

Regards,

Ken Wagner

**Comment by beaucoder** [comment] 2017-01-02 12:18
Yeah, exactly. Thanks for your efforts and promptness.

Regards,

Ken Wagner

**Comment by beaucoder** [comment] 2017-01-02 12:20
No, No, No!!

Only 150 to 260 lines ever print. It varies.

Does not matter if the query is simple (select * from xxx;) or complex.

For testing you can use the 3503 row query if you wish.

Huba Nagy is also working on this. TYLTK.

Regards,

Ken Wagner

**Comment by ioquatix** [comment] 2017-02-01 21:55
@beaucoder I've updated to `node-pty` and I can't reproduce this issue on macOS. I'll also test on linux. It's released as v2.1.0 today.

**Comment by ioquatix** [comment] 2017-02-19 05:19
@beaucoder Can you please check if this is still an issue, and if it is let us know.

**Closed by ioquatix** 2017-02-19 05:19 UTC
